project_id = "ldiadiezzooivgittjvj"

[functions.sync-tables]
verify_jwt = true

[functions.sync-itbi-prefeitura]
verify_jwt = true

[functions.import-itbi]
verify_jwt = true

[functions.sync-itbi-daily]
verify_jwt = false

[functions.import-csv-itbi]
verify_jwt = true

[functions.seed-condominios]
verify_jwt = true

[functions.chat-mercado]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false
