import { jsPDF } from "jspdf";
import { writeFileSync } from "node:fs";
const d = new jsPDF({unit:"mm",format:"a4"});
d.setFont("helvetica","bold"); d.setFontSize(14);
d.text("ABCDEFGHIJKLMNOPQRSTUVWXYZ",15,20);
d.text("HELLO WORLD MILLION INDIVIDUAL",15,30);
d.setFont("helvetica","normal");
d.text("ABCDEFGHIJKLMNOPQRSTUVWXYZ",15,42);
d.text("HELLO WORLD MILLION INDIVIDUAL",15,50);
writeFileSync("/tmp/ft2.pdf",Buffer.from(d.output("arraybuffer")));
