-- Expandir base de conhecimento da Sofia com mais artigos especializados

-- FINANCIAMENTO
INSERT INTO public.sofia_knowledge_base (category, title, content, keywords, source) VALUES
('financiamento', 'Tipos de Financiamento Imobiliário', 'No Brasil, existem três principais tipos de financiamento imobiliário: 1) SFH (Sistema Financeiro de Habitação): usa recursos do FGTS e poupança, com limite de R$ 1,5 milhão, taxa máxima de TR + 12% a.a., permite usar FGTS. 2) SFI (Sistema Financeiro Imobiliário): sem limite de valor, taxas de mercado, ideal para imóveis de alto padrão. 3) MCMV/Casa Verde Amarela: programa habitacional com subsídios para famílias de baixa renda. Para Barra da Tijuca, a maioria dos imóveis usa SFI devido aos valores acima do limite SFH.', ARRAY['financiamento', 'sfh', 'sfi', 'mcmv', 'fgts', 'taxa', 'juros'], 'Lei nº 4.380/1964'),

('financiamento', 'Documentos para Financiamento Bancário', 'Documentos pessoais necessários: RG, CPF, comprovante de residência, comprovante de renda (holerite, IR, extrato bancário), certidão de casamento/nascimento. Documentos do imóvel: matrícula atualizada (30 dias), certidão negativa de ônus, IPTU, habite-se, planta aprovada. O banco faz avaliação do imóvel e análise de crédito do comprador. Prazo médio de aprovação: 30-45 dias.', ARRAY['documentos', 'banco', 'financiamento', 'aprovação', 'crédito'], NULL),

('financiamento', 'Cálculo de Capacidade de Financiamento', 'A capacidade de financiamento considera: 1) Comprometimento máximo de 30% da renda bruta familiar. 2) Idade do comprador (prazo máximo = 80 anos - idade atual). 3) Score de crédito. Exemplo: família com renda de R$ 30.000 pode comprometer até R$ 9.000/mês em parcelas. Com prazo de 30 anos e taxa de 10% a.a., isso permite financiar aproximadamente R$ 1.100.000. O restante deve ser dado como entrada (mínimo 20% do valor).', ARRAY['capacidade', 'renda', 'parcela', 'prazo', 'entrada'], NULL),

-- CONTRATOS
('contratos', 'Contrato de Compra e Venda de Imóvel', 'O contrato de compra e venda deve conter: 1) Qualificação completa das partes (CPF, RG, estado civil, profissão). 2) Descrição detalhada do imóvel (matrícula, endereço, área, vagas). 3) Preço e forma de pagamento. 4) Cláusulas de rescisão e multa (geralmente 10-20%). 5) Responsabilidade por tributos e despesas. 6) Prazo para escritura e entrega. Sempre exija arras confirmatórias (sinal) para garantir a operação.', ARRAY['contrato', 'compra', 'venda', 'cláusulas', 'arras', 'sinal'], 'Código Civil Art. 481-532'),

('contratos', 'Promessa de Compra e Venda vs Escritura', 'A Promessa de Compra e Venda é um contrato preliminar que obriga as partes a celebrar a escritura definitiva. Pode ser registrada no cartório de imóveis para oponibilidade a terceiros (Art. 1.417 CC). A Escritura Pública é o contrato definitivo, lavrado em cartório de notas, obrigatório para imóveis acima de 30 salários mínimos. Sem registro na matrícula, a propriedade não se transfere (Art. 1.245 CC).', ARRAY['promessa', 'escritura', 'registro', 'matrícula', 'cartório'], 'Código Civil Art. 1.245, 1.417'),

('contratos', 'Cláusulas Essenciais de Locação', 'Lei do Inquilinato (8.245/91) estabelece: 1) Prazo mínimo de 30 meses para proteção do locatário. 2) Índice de reajuste (geralmente IGP-M ou IPCA). 3) Garantias: caução (3 meses), fiador, seguro-fiança. 4) Multa proporcional por rescisão antecipada. 5) Responsabilidade por reformas (locador: estruturais; locatário: conservação). 6) Vistoria de entrada e saída obrigatória. Contrato verbal é válido mas não recomendado.', ARRAY['locação', 'aluguel', 'inquilinato', 'garantia', 'fiador', 'reajuste'], 'Lei nº 8.245/1991'),

-- DUE DILIGENCE AVANÇADO
('due_diligence', 'Análise de Risco Jurídico Completa', 'Due diligence imobiliária completa inclui: 1) Análise da matrícula (últimos 20 anos de transações). 2) Certidões do vendedor (pessoa física ou jurídica): cíveis, criminais, trabalhistas, federais. 3) Certidões do imóvel: ônus reais, ações reipersecutórias, débitos fiscais. 4) Análise societária (se PJ): contrato social, poderes dos representantes. 5) Verificação urbanística: uso do solo, licenças, habite-se. O custo da due diligence é irrisório comparado aos riscos evitados.', ARRAY['due diligence', 'risco', 'certidões', 'análise', 'jurídico'], NULL),

('due_diligence', 'Alertas de Fraude Imobiliária', 'Sinais de alerta em transações: 1) Vendedor com pressa excessiva ou desconto muito agressivo. 2) Matrícula com múltiplas transferências recentes. 3) Procuração com poderes amplos sem reconhecimento de firma. 4) Imóvel ocupado por terceiros sem contrato. 5) Divergência entre área real e registrada. 6) Vendedor que evita fornecer documentação completa. Sempre verifique a autenticidade das certidões diretamente nos órgãos emissores.', ARRAY['fraude', 'golpe', 'alerta', 'verificação', 'segurança'], NULL),

('due_diligence', 'Regularização de Imóveis', 'Procedimentos para regularização: 1) Imóvel sem habite-se: contratar engenheiro para laudo técnico e solicitar licenciamento. 2) Área construída não averbada: retificação de área no cartório. 3) Imóvel em inventário: aguardar partilha ou comprar direitos hereditários (maior risco). 4) Usufruto: verificar extinção por morte ou renúncia. 5) Penhora: negociar quitação ou aguardar leilão. Regularização pode demorar de 6 meses a 2 anos.', ARRAY['regularização', 'habite-se', 'inventário', 'penhora', 'usufruto'], NULL),

-- LEGISLAÇÃO ADICIONAL
('legislacao', 'Direito de Preferência na Locação', 'O locatário tem direito de preferência na compra do imóvel alugado (Art. 27 Lei 8.245/91). O locador deve notificar por escrito com todas as condições do negócio. Prazo para exercício: 30 dias. Se violado, locatário pode: 1) Haver para si o imóvel (se registrado contrato há mais de 30 meses). 2) Receber perdas e danos. Não se aplica a venda judicial, permuta, ou doação.', ARRAY['preferência', 'locação', 'compra', 'locatário', 'notificação'], 'Lei nº 8.245/1991 Art. 27-34'),

('legislacao', 'Imposto de Transmissão (ITBI)', 'ITBI é imposto municipal devido na transmissão onerosa de imóveis. No Rio de Janeiro: alíquota de 3% sobre o valor venal ou valor declarado (o maior). Base de cálculo pode ser contestada administrativamente. Isenções: primeira aquisição de imóvel residencial até determinado valor (verificar legislação municipal vigente). ITBI deve ser pago antes da lavratura da escritura. O pagamento é condição para registro da transmissão.', ARRAY['itbi', 'imposto', 'transmissão', 'alíquota', 'isenção'], 'CTN Art. 35-42'),

('legislacao', 'Responsabilidade do Corretor de Imóveis', 'O corretor responde por: 1) Informações falsas ou omissões relevantes sobre o imóvel. 2) Negligência na verificação documental básica. 3) Intermediação de negócio com pessoa sem legitimidade. Lei 6.530/78 exige inscrição no CRECI. Comissão: 6% (venda) e 1 aluguel (locação), conforme tabela CRECI. Contrato de corretagem deve especificar exclusividade, prazo, e condições de pagamento.', ARRAY['corretor', 'responsabilidade', 'creci', 'comissão', 'corretagem'], 'Lei nº 6.530/1978'),

-- AVALIAÇÃO AVANÇADO
('avaliacao', 'Fatores de Valorização Imobiliária', 'Principais fatores que influenciam o valor: 1) Localização: proximidade de praia, metrô, shopping, escolas. 2) Vista e orientação solar: mar, montanha, sol da manhã. 3) Andar e posição no edifício: andares altos valem 2-5% a mais por andar. 4) Conservação e modernização: reforma recente adiciona 10-20%. 5) Infraestrutura do condomínio: lazer completo, segurança 24h. 6) Vagas de garagem: cada vaga extra vale R$ 50-150 mil na Barra.', ARRAY['valorização', 'fatores', 'preço', 'localização', 'vista'], NULL),

('avaliacao', 'Depreciação de Imóveis', 'Fatores de depreciação: 1) Idade do imóvel: prédios antigos (>30 anos) podem ter desconto de 15-25%. 2) Falta de manutenção: infiltrações, fachada degradada. 3) Problemas estruturais: trincas, recalque. 4) Layout obsoleto: dependência de empregada sem uso moderno. 5) Unidade nos primeiros andares sem vista. 6) Pendências documentais ou jurídicas. Na Barra, imóveis da década de 80 valem 20-30% menos que lançamentos novos equivalentes.', ARRAY['depreciação', 'desvalorização', 'idade', 'conservação', 'problema'], NULL),

('avaliacao', 'Metodologia NBR 14653', 'A norma NBR 14653-2 estabelece métodos de avaliação: 1) Comparativo direto de dados de mercado: mais usado, compara transações similares. 2) Involutivo: viabilidade econômica do terreno. 3) Evolutivo: custo de reprodução. 4) Renda: capitalização de aluguel. Para imóveis residenciais, o método comparativo é preferido. Laudo completo exige: mínimo 5 amostras, homogeneização de valores, cálculo de intervalo de confiança.', ARRAY['nbr', 'metodologia', 'avaliação', 'laudo', 'comparativo'], 'ABNT NBR 14653-2'),

-- MERCADO
('mercado', 'Ciclos do Mercado Imobiliário', 'O mercado imobiliário segue ciclos de aproximadamente 7-10 anos: 1) Recuperação: preços estagnados, oportunidades de compra. 2) Expansão: preços em alta, lançamentos aquecidos. 3) Superoferta: muitos imóveis à venda, preços começam a cair. 4) Recessão: queda de preços, negociações mais difíceis. Na Barra da Tijuca, o último pico foi em 2014, seguido de correção até 2019. A partir de 2021, novo ciclo de recuperação.', ARRAY['ciclo', 'mercado', 'tendência', 'preço', 'oportunidade'], NULL),

('mercado', 'Indicadores do Mercado Imobiliário', 'Principais indicadores para análise: 1) Preço médio por m² (fonte: ITBI, FIPEZAP). 2) Velocidade de vendas: tempo médio até venda (VSO). 3) Taxa de vacância: imóveis desocupados. 4) Lançamentos vs. Vendas: absorção do mercado. 5) Taxa de juros Selic: impacta custo do financiamento. 6) Índices de confiança (CBIC, ABRAINC). Na Barra, o preço médio residencial em 2025 está entre R$ 12.000-18.000/m² conforme localização.', ARRAY['indicadores', 'análise', 'preço', 'mercado', 'fipezap'], NULL);
