-- Inserir microbairros para Recreio, Zona Sul, Zona Norte e Jacarepaguá
-- Total: ~45 microbairros

-- ===================
-- RECREIO DOS BANDEIRANTES (5 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Orla Recreio', 'RECREIO DOS BANDEIRANTES', ARRAY['LUCIO COSTA', 'LÚCIO COSTA', 'SERNAMBETIBA', 'GILKA MACHADO', 'GLAUCIO GIL']),
('Pontal', 'RECREIO DOS BANDEIRANTES', ARRAY['PONTAL', 'TIM MAIA', 'HENFIL', 'PREFEITO MENDES DE MORAIS', 'BARRA DE GUARATIBA']),
('Gleba A', 'RECREIO DOS BANDEIRANTES', ARRAY['ALFREDO BALTHAZAR', 'GENARO DE CARVALHO', 'JOSE LUIZ FERRAZ', 'JOSÉ LUIZ FERRAZ', 'BETO BRAVO', 'JORNALISTA HENRIQUE CORDEIRO']),
('Gleba B', 'RECREIO DOS BANDEIRANTES', ARRAY['SILVIA POZZANA', 'BENVINDO DE NOVAES', 'TEIXEIRA HEIZER', 'LUIZ CARLOS SAROLLI', 'ADILSON MAGALHAES', 'ROBERTO BURLE MARX']),
('Eixo Américas Recreio', 'RECREIO DOS BANDEIRANTES', ARRAY['SALVADOR ALLENDE', 'GUIOMAR NOVAES', 'ROBERTO MARINHO']);

-- ===================
-- COPACABANA (4 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Orla Copacabana', 'COPACABANA', ARRAY['ATLANTICA', 'ATLÂNTICA', 'AVENIDA ATLANTICA']),
('Copacabana Centro', 'COPACABANA', ARRAY['NOSSA SENHORA DE COPACABANA', 'N S DE COPACABANA', 'SIQUEIRA CAMPOS', 'SANTA CLARA', 'FIGUEIREDO MAGALHAES', 'FIGUEIREDO MAGALHÃES']),
('Leme', 'COPACABANA', ARRAY['PRAIA DO LEME', 'GUSTAVO SAMPAIO', 'ANCHIETA', 'GENERAL RIBEIRO DA COSTA', 'LEME']),
('Posto 5/6', 'COPACABANA', ARRAY['BARATA RIBEIRO', 'DOMINGOS FERREIRA', 'PRADO JUNIOR', 'SOUZA LIMA', 'RODOLFO DANTAS', 'TONELERO']);

-- ===================
-- IPANEMA (4 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Orla Ipanema', 'IPANEMA', ARRAY['VIEIRA SOUTO', 'FRANCISCO OTAVIANO', 'PRUDENTE DE MORAIS']),
('Ipanema Centro', 'IPANEMA', ARRAY['VISCONDE DE PIRAJA', 'VISCONDE DE PIRAJÁ', 'GARCIA DAVILA', 'GARCIA D''AVILA', 'MARIA QUITERIA', 'MARIA QUITÉRIA']),
('General Osório', 'IPANEMA', ARRAY['FARME DE AMOEDO', 'VINICIUS DE MORAES', 'VINÍCIUS DE MORAES', 'TEIXEIRA DE MELO', 'JOANA ANGELICA', 'JOANA ANGÉLICA']),
('Jardim de Alah', 'IPANEMA', ARRAY['HENRIQUE DUMONT', 'EPITACIO PESSOA', 'EPITÁCIO PESSOA', 'RAINHA ELIZABETH', 'BORGES DE MEDEIROS']);

-- ===================
-- LEBLON (3 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Orla Leblon', 'LEBLON', ARRAY['DELFIM MOREIRA', 'AV DELFIM', 'AVENIDA DELFIM']),
('Leblon Centro', 'LEBLON', ARRAY['ATAULFO DE PAIVA', 'DIAS FERREIRA', 'CARLOS GOES', 'CARLOS GÓES', 'GENERAL URQUIZA', 'RITA LUDOLF']),
('Alto Leblon', 'LEBLON', ARRAY['VISCONDE DE ALBUQUERQUE', 'BARTOLOMEU MITRE', 'GENERAL SAN MARTIN', 'GENERAL VENANCIO FLORES']);

-- ===================
-- BOTAFOGO (4 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Orla Botafogo', 'BOTAFOGO', ARRAY['PRAIA DE BOTAFOGO', 'PRAIA BOTAFOGO', 'SENADOR VERGUEIRO']),
('Botafogo Centro', 'BOTAFOGO', ARRAY['VOLUNTARIOS DA PATRIA', 'VOLUNTÁRIOS DA PÁTRIA', 'SAO CLEMENTE', 'SÃO CLEMENTE', 'NELSON MANDELA', 'PASSAGEM']),
('Humaitá', 'BOTAFOGO', ARRAY['HUMAITA', 'HUMAITÁ', 'VISCONDE DE CARAVELAS', 'MATRIZ']),
('Real Grandeza', 'BOTAFOGO', ARRAY['REAL GRANDEZA', 'BAMBINA', 'MUNIZ BARRETO', 'DA PASSAGEM']);

-- ===================
-- FLAMENGO (3 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Orla Flamengo', 'FLAMENGO', ARRAY['PRAIA DO FLAMENGO', 'RUI BARBOSA', 'BEIRA MAR', 'PARQUE DO FLAMENGO']),
('Flamengo Centro', 'FLAMENGO', ARRAY['MARQUES DE ABRANTES', 'PAISSANDU', 'MACHADO DE ASSIS', 'CORREIA DUTRA', 'DOIS DE DEZEMBRO']),
('Largo do Machado', 'FLAMENGO', ARRAY['SENADOR VERGUEIRO', 'DO CATETE', 'FERREIRA VIANA', 'TAVARES BASTOS', 'LARGO DO MACHADO']);

-- ===================
-- LARANJEIRAS (2 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Laranjeiras Centro', 'LARANJEIRAS', ARRAY['DAS LARANJEIRAS', 'IPIRANGA', 'ALICE', 'GENERAL GLICERIO', 'GENERAL GLICÉRIO', 'PEREIRA DA SILVA']),
('Cosme Velho', 'LARANJEIRAS', ARRAY['COSME VELHO', 'CORCOVADO', 'ALTO DAS LARANJEIRAS', 'SILVEIRA MARTINS']);

-- ===================
-- TIJUCA (4 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Tijuca Centro', 'TIJUCA', ARRAY['CONDE DE BONFIM', 'HADDOCK LOBO', 'JOSE HIGINO', 'JOSÉ HIGINO', 'DOUTOR SATAMINI']),
('Praça Saens Peña', 'TIJUCA', ARRAY['URUGUAI', 'MARIZ E BARROS', 'DESEMBARGADOR ISIDRO', 'DESEMBARGADOR IZIDRO', 'SAENS PENA', 'SAENS PEÑA']),
('Alto da Boa Vista', 'TIJUCA', ARRAY['BOA VISTA', 'FURNAS', 'EXCELSIOR', 'ALMIRANTE ALEXANDRINO']),
('Usina', 'TIJUCA', ARRAY['USINA', 'MAXWELL', 'PROFESSOR MANOEL DE ABREU', 'SAO FRANCISCO XAVIER', 'SÃO FRANCISCO XAVIER']);

-- ===================
-- VILA ISABEL (3 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Boulevard', 'VILA ISABEL', ARRAY['BOULEVARD 28 DE SETEMBRO', '28 DE SETEMBRO', 'VISCONDE DE SANTA ISABEL']),
('Vila Isabel Centro', 'VILA ISABEL', ARRAY['ALEXANDRE MACKENZIE', 'TEODORO DA SILVA', 'BARAO DE SAO FRANCISCO', 'BARÃO DE SÃO FRANCISCO', 'SOUZA FRANCO']),
('Maracanã', 'VILA ISABEL', ARRAY['MARACANA', 'MARACANÃ', 'PROF EURICO RABELO', 'PROFESSOR EURICO RABELO', 'CONSELHEIRO OLEGARIO']);

-- ===================
-- GRAJAÚ (2 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Grajaú Centro', 'GRAJAÚ', ARRAY['GRAJAU', 'GRAJAÚ', 'BARAO DE MESQUITA', 'BARÃO DE MESQUITA', 'EDGAR ROMERO', 'ENGENHEIRO ARTUR MOURA']),
('Alto Grajaú', 'GRAJAÚ', ARRAY['SERRA DO GRAJAU', 'SERRA DO GRAJAÚ', 'ITACURUCA', 'ITACURUÇA', 'AURORA', 'ANDARAI', 'ANDARAÍ']);

-- ===================
-- MÉIER (3 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Méier Centro', 'MÉIER', ARRAY['DIAS DA CRUZ', 'VINTE E QUATRO DE MAIO', '24 DE MAIO', 'ARQUIAS CORDEIRO', 'CAROLINA MACHADO']),
('Rua Coelho Neto', 'MÉIER', ARRAY['RUI BARBOSA', 'COELHO NETO', 'AMARO CAVALCANTI', 'PADRE MANOEL DA NOBREGA']),
('Lins', 'MÉIER', ARRAY['LINS DE VASCONCELOS', 'BOULEVARD 28 DE SETEMBRO']);

-- ===================
-- JACAREPAGUÁ / FREGUESIA (6 microbairros)
-- ===================
INSERT INTO microbairros_geo (nome, bairro, keywords) VALUES
('Freguesia Centro', 'FREGUESIA (JACAREPAGUÁ)', ARRAY['TRES RIOS', 'TRÊS RIOS', 'ARAGUAIA', 'JACAREPAGUA', 'JACAREPAGUÁ', 'BARÃO']),
('Anil', 'JACAREPAGUÁ', ARRAY['BANDEIRANTES', 'GEREMARIO DANTAS', 'GEREMÁRIO DANTAS', 'CANDIDO BENICIO', 'CÂNDIDO BENÍCIO']),
('Taquara Centro', 'TAQUARA', ARRAY['PROF AMARAL', 'PROFESSOR AMARAL', 'GAZEL FILHO', 'NELSON CARDOSO', 'CAMPINHO']),
('Tanque', 'JACAREPAGUÁ', ARRAY['TIROL', 'GUANUMBI', 'BARONESA', 'CAMPISTA']),
('Pechincha Centro', 'PECHINCHA', ARRAY['RETIRO DOS ARTISTAS', 'COMANDANTE RUBENS SILVA', 'ARTUR RIOS']),
('Curicica', 'JACAREPAGUÁ', ARRAY['JOSE WILLKER', 'JOSÉ WILLKER', 'JAIME POGGI', 'ESTRADA DOS BANDEIRANTES']);